### ISSUE TITLE
Support WASI(WebAssembly System Interface).

### ISSUE THREAD

**Issue by mohanson** [mohanson/pywasm#25]
docs: https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md

The WASI is still not stable. But it's not a big work, so, add this?

**Comment by ouwenkg** [comment]
First issue :smiley:

**Comment by mohanson** [comment]
No, it's second.

**Comment by pmp-p** [comment]
any progress ?
i'd love to have a wasi python polyfill for running micropython-wasi browser test suite

**Comment by mohanson** [comment]
@pmp-p It is in my TODO list, but now I don't have the energy to do it. Maybe after a few months, when I am free.

**Comment by kanaka** [comment]
In addition to the WASI specs, I suspect this could be used as a reference: https://github.com/devsnek/node-wasi It's an implementation of the WASI interface in JS and uses some C bindings as well.

**Comment by pmp-p** [comment]
Some more pointers about wasi polyfill https://github.com/bytecodealliance/wasi.dev/pull/11

and after some personnal python polyfill tests i'd say that a usefull tool for implementation would certainly be https://github.com/aguinet/dragonffi

**Comment by mohanson** [comment]
@pmp-p  Are you interested in trying to complete this feature?

In fact, in another project of mine, I completed entire WASI, with about 1,000 lines of code: https://github.com/mohanson/wasc/blob/master/src/platform/posix_x86_64_wasi.h

But it can't be used directly on pywasm, because I wrote it for the `wasc` project and that only supports `x86` and `risc-v` platforms.

All the work is to find a useful wasi c library, and then glue them with ffi, just like you said.

**Comment by vshymanskyy** [comment]
In wasm3, we're using `uvwasi` as the default WASI API provider.

**Comment by pmp-p** [comment]
@vshymanskyy i'm specifically interested in *browser* polyfills ( which can't return i64 actually because wasm32 ), though i want to use wasm3 on android for cpython/wapy modules or even full interpreter sandboxing.

@mohanson i'll have to, since i want to run  cpython/wapy wasm testsuite somehow.

**Comment by vshymanskyy** [comment]
For Browsers, we should reach BigInt epoch pretty soon. For Android, libuv should be pretty solid.
As for WASI envirnoment for Browsers, Wasmer has a privided a nice polyfill, and they also created https://webassembly.sh
