### ISSUE TITLE
Issues with importing libraries

### ISSUE THREAD

**Issue by nilax97** [mohanson/pywasm#26]
I am trying to analyse polybench suite (written in C)

Since none of your test files contain any #include, wanted to know what to do in case of such cases.

Used emscripten to comile to _.c_ files to _.wasm_

On trying to load the file in pyawm using _pywasm.load("filename")_

Getting the following error:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-ac0b06bea133> in <module>
----> 1 vm = pywasm.load('polybench-c-4.1/2mm.wasm')

/usr/local/lib/python3.7/site-packages/pywasm/__init__.py in load(name, imps)
     69     with open(name, 'rb') as f:
     70         module = structure.Module.from_reader(f)
---> 71         return VirtualMachine(module, imps)
     72 
     73 

/usr/local/lib/python3.7/site-packages/pywasm/__init__.py in __init__(self, module, imps)
     15         for e in self.module.imports:
     16             if e.module not in imps or e.name not in imps[e.module]:
---> 17                 raise Exception(f'pywasm: global import {e.module}.{e.name} not found')
     18             if e.kind == convention.extern_func:
     19                 a = execution.HostFunc(self.module.types[e.desc], imps[e.module][e.name])

Exception: pywasm: global import env.calloc not found

**Comment by mohanson** [comment]
But at the same time pywasm provides a way for you to implement libc's functions yourself, The above code can be run with:

```py
import pywasm


def calloc(ctx: pywasm.Ctx, n: int, size: int):
    s = ctx.mems[0].size - 1
    ctx.mems[0].grow(n * size)
    return s


vm = pywasm.load("/tmp/program.wasm", imps={'env': {
    'calloc': calloc
}})
r = vm.exec('main', [])
print(r)
```

**Comment by nilax97** [comment]
Thanks. I found some workaround in emcc compilation :

```
emcc -static
```

Which reduces the number of imports in the code. The corresponding _file.wat_ is:

```
(module
  (type (;0;) (func (param i32 i32 i32) (result i32)))
  (type (;1;) (func (param i32 f64 i32 i32 i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32)))
  (type (;3;) (func (param i32 i64 i32) (result i64)))
  (import "wasi_unstable" "fd_close" (func (;0;) (type 4)))
  (import "wasi_unstable" "fd_write" (func (;1;) (type 5)))
  (import "env" "__syscall140" (func (;2;) (type 6)))
  (import "wasi_unstable" "proc_exit" (func (;3;) (type 8)))
.....
.....
```

All these compilations are for the [polybench suite 4.1](http://web.cse.ohio-state.edu/~pouchet.2/software/polybench/#download) compiled using [emscripten](https://emscripten.org/)

As per this [link](https://github.com/emscripten-core/emscripten/issues/9479) __syscall140 corresponds to env.fd_seek. 

So for the following descriptors, these are all functions from wasi. 
Will implementing their corresponding libc functions be sufficient for the same?

**Comment by mohanson** [comment]
Well, in fact it (WASI) is in my TODO list. It has been delayed for too long

See #25 

So at the moment, you may not run this test on pywasm, sorry.
