### ISSUE TITLE
Limiting the number of instruction steps

### ISSUE THREAD

**Issue by void4** [mohanson/pywasm#35]
The [Life](https://github.com/perlin-network/life/issues/52) WebAssembly VM supports setting instruction step ("gas") and memory allocation limits. Would this be possible to implement in pywasm too?

Use cases:

- avoiding deliberate or accidental resource exhaustion
- setting a limit in competitions involving .wasm executables

**Comment by mohanson** [comment]
A good idea, I will try to realize it.

The initial plan is to add an `option` parameter to the `pywasm.load` and `runtime.exec` functions.

**Comment by mohanson** [comment]
I released version 1.0.4 now

About how you can limit cycle consumption: https://github.com/mohanson/pywasm/blob/master/examples/cycle.py
Also you can set `option.pages_limit` to limit memory(note: 1 page == 64 KB).

**Comment by void4** [comment]
This is frickin cool! 

I'm thinking of using this for a tiny chess engine tournament https://github.com/void4/notes/issues/70 or in a system that verifies and rewards mathematical proofs: https://github.com/void4/notes/issues/65

Thank you :)

**Comment by mohanson** [comment]
There was a problem with my release script, which has been fixed now. Please reinstall `pywasm==1.0.5` :)
