### ISSUE TITLE
API Documents

### ISSUE THREAD

**Issue by prescod** [mohanson/pywasm#36]
Are there any docs (perhaps at least auto-generated docs) describing what pywasm.Memory, pywasm.Limits, etc. are?

**Comment by mohanson** [comment]
Not currently, all the documents are inside the code.

About Memory: https://github.com/mohanson/pywasm/blob/master/pywasm/execution.py#L226

About Limits: https://github.com/mohanson/pywasm/blob/master/pywasm/binary.py#L75
