### ISSUE TITLE
Exception: pywasm: missing import env.time

### ISSUE THREAD

**Issue by cxs1427** [mohanson/pywasm#39]
大佬，这个报错是怎么回事，第一次接触wasm，不太懂

```python
----> 1 pywasm.load('Wasm.wasm')

d:\python\lib\site-packages\pywasm\__init__.py in load(name, imps, opts)
     97     with open(name, 'rb') as f:
     98         module = binary.Module.from_reader(f)
---> 99         return Runtime(module, imps, opts)
    100
    101

d:\python\lib\site-packages\pywasm\__init__.py in __init__(self, module, imps, opts)
     26         for e in module.import_list:
     27             if e.module not in imps or e.name not in imps[e.module]:
---> 28                 raise Exception(f'pywasm: missing import {e.module}.{e.name}')
     29             if isinstance(e.desc, binary.TypeIndex):
     30                 a = execution.HostFunc(module.type_list[e.desc], imps[e.module][e.name])

Exception: pywasm: missing import env.time
```

加载的wasm文件 ☛ https://spa14.scrape.center/Wasm.wasm

**Comment by mohanson** [comment]
```
  (import "env" "time" (func (;0;) (type 0)))
  (import "env" "__cxa_allocate_exception" (func (;1;) (type 0)))
  (import "env" "__cxa_throw" (func (;2;) (type 5)))
  (import "env" "abort" (func (;3;) (type 10)))
  (import "env" "emscripten_resize_heap" (func (;4;) (type 0)))
  (import "env" "emscripten_memcpy_big" (func (;5;) (type 4)))
  (import "env" "memory" (memory (;0;) 256 256))
```

可以看到代码中导入了外部函数, 而这些外部函数并未提供给 pywasm, 以这种方式编译的 emscripten 程序只能在 emscripten 提供的 js 环境下运行(可以想象 pywasm 是一个 CPU, 你无法问 CPU 要当前的时间, 只能向搭载 CPU 的操作系统要时间

如果你的源代码是 C 的话, 可以用 wasi-sdk 进行编译, 并带上 --no-standard-libraries 编译参数, 同时确保你没有在 C 代码中进行任何系统调用(例如 printf, get_time...). 或者先使用这个在线编译器 https://wasdk.github.io/WasmFiddle/ 试试.

**Comment by cxs1427** [comment]
> ```
>   (import "env" "time" (func (;0;) (type 0)))
>   (import "env" "__cxa_allocate_exception" (func (;1;) (type 0)))
>   (import "env" "__cxa_throw" (func (;2;) (type 5)))
>   (import "env" "abort" (func (;3;) (type 10)))
>   (import "env" "emscripten_resize_heap" (func (;4;) (type 0)))
>   (import "env" "emscripten_memcpy_big" (func (;5;) (type 4)))
>   (import "env" "memory" (memory (;0;) 256 256))
> ```
> 
> 可以看到代码中导入了外部函数, 而这些外部函数并未提供给 pywasm, 以这种方式编译的 emscripten 程序只能在 emscripten 提供的 js 环境下运行(可以想象 pywasm 是一个 CPU, 你无法问 CPU 要当前的时间, 只能向搭载 CPU 的操作系统要时间
> 
> 如果你的源代码是 C 的话, 可以用 wasi-sdk 进行编译, 并带上 --no-standard-libraries 编译参数, 同时确保你没有在 C 代码中进行任何系统调用(例如 printf, get_time...). 或者先使用这个在线编译器 https://wasdk.github.io/WasmFiddle/ 试试.

好的，我再研究研究，感谢~

**Comment by cxs1427** [comment]
> ```
>   (import "env" "time" (func (;0;) (type 0)))
>   (import "env" "__cxa_allocate_exception" (func (;1;) (type 0)))
>   (import "env" "__cxa_throw" (func (;2;) (type 5)))
>   (import "env" "abort" (func (;3;) (type 10)))
>   (import "env" "emscripten_resize_heap" (func (;4;) (type 0)))
>   (import "env" "emscripten_memcpy_big" (func (;5;) (type 4)))
>   (import "env" "memory" (memory (;0;) 256 256))
> ```
> 
> 可以看到代码中导入了外部函数, 而这些外部函数并未提供给 pywasm, 以这种方式编译的 emscripten 程序只能在 emscripten 提供的 js 环境下运行(可以想象 pywasm 是一个 CPU, 你无法问 CPU 要当前的时间, 只能向搭载 CPU 的操作系统要时间
> 
> 如果你的源代码是 C 的话, 可以用 wasi-sdk 进行编译, 并带上 --no-standard-libraries 编译参数, 同时确保你没有在 C 代码中进行任何系统调用(例如 printf, get_time...). 或者先使用这个在线编译器 https://wasdk.github.io/WasmFiddle/ 试试.

大佬，你说的 emscripten可以在python代码中调用吗，比如像 subproess调用node子进程那样
