### ISSUE TITLE
Continuation of supplying a memory instance to a function before execution

### ISSUE THREAD

**Issue by prescod** [mohanson/pywasm#40]
Finishing up #38 

Can you clarify whether pywasm supports a pattern like this?

```
memory = pywasm.Memory(pywasm.binary.MemoryType(pywasm.binary.Limit(min=1, max=10)))

runtime = pywasm.load('test/malloc.wasm', {'env': {'memory': memory}})
```

How does one express a memory limit for a WASM runtime?

**Comment by mohanson** [comment]
This feature is supported, and your code has no errors. There are some examples in the test case about how to import external instances:

https://github.com/mohanson/pywasm/blob/master/test/test_spec.py#L68-L89

**Comment by prescod** [comment]
Is there any reason that Limits doesn't take an argument?

https://github.com/mohanson/pywasm/issues/41
