### ISSUE TITLE
Allow "minimum" and "maximum" in constructor for Limits object

### ISSUE THREAD

**Issue by prescod** [mohanson/pywasm#41]
https://github.com/mohanson/pywasm/blob/8cb78724d00014a36e5eb4c8c60ab6dd1a1aad6c/pywasm/binary.py#L80

I'd suggest these be called "minimum" and "maximum" rather than "n" and "m".

**Comment by mohanson** [comment]
Well, let me think about it, because doing so will break compatibility.

**Comment by prescod** [comment]
If you agree that it is a good direction I can try to implement it in a backwards-compatible way. I just do not do the work if you are not interested in the change.
