### ISSUE TITLE
Cannot use "from pywasm import allocate_bytes, write_to_memory, address_to_utf8" 

### ISSUE THREAD

**Issue by INPUTrrr0** [mohanson/pywasm#53]
Hi. I'm trying to pass an array from python to wasm and I came a cross a tutorial suggesting the use of pywasm, with the import line " "from pywasm import allocate_bytes, write_to_memory, address_to_utf8". However, I get an import error. Please let me know how to fix it and be able to import memory from python to wasm. Thanks!

**Comment by mohanson** [comment]
Weird tutorial, I don't remember ever writing code like this for pywasm.

If you want to pass in an array to wasm via python, remember one thing, any data is stored in bytes in memory. Therefore, you need to do two things:

1. In the Wasm code, tell Python where in memory I plan to start reading (and the length).
2. In the Python code, serialize your array into a byte array and write it into the memory obtained in the first step.

An example:

```c
// Build: clang-16 --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-all -Wl,--allow-undefined -o main.wasm main.c
#include <stdint.h>

extern int load_data(uint8_t* addr, int n);

int handle_data() {
  uint8_t data[64] = {};
  if (data[0] == 0xff) {
    return 1;
  }
  load_data(data, 64);
  if (data[0] != 0xff) {
    return 1;
  }
  return 0;
}
```

```py
import pywasm

def load_data(s: pywasm.Store, addr: int, n: int):
    for i in range(n):
        s.mems[0].data[addr + i] = 0xff
    return n

runtime = pywasm.load('main.wasm', {'env': {'load_data': load_data}})
r = runtime.exec('handle_data', [])
print(r)  # 0
```
